// mypages.js
// 2023-03-01: by mi

exports.genMainPage = function(lista, data){
    var pagHTML = `
    <!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>About people</title>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">

        <header class="w3-container w3-pale-red w3-center">
          <h1>Lista de pessoas na Base de Dados (${lista.length})</h1>
        </header>

        <div class="w3-container">
            <table class="w3-table-all w3-centered w3-hoverable w3-large">
            <tr>
              <th>Id</th>
              <th>Nome</th>
              <th>Idade</th>
              <th>Sexo</th>
              <th>Cidade</th>
            </tr>`

    for(let i = 0; i < lista.length; i++){
        pagHTML+=
            `<tr>
                <td>${lista[i].id}</td>
                <td>
                    <a href="http://localhost:7777/pessoas/${lista[i].id}">${lista[i].nome}</a>
                </td>
                <td>${lista[i].idade}</td>
                <td>${lista[i].sexo}</td>
                <td>${lista[i].morada.cidade}</td>
            </tr>`
    }


    pagHTML+= `
            </table>
        </div>

        <footer class="w3-container w3-pale-red w3-center">
          <h5>Generated by pessoas-server: ${data}</h5>
          <h4><a href="http://localhost:7777/">Voltar ao Menu</a><h4>
        </footer>

        </div>
        
    </body>
</html>
    `

    return pagHTML
}

exports.genPessoaPage = function(pessoa, data){

   

    var pagHTML = `
    <!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>About people</title>
        <link rel="stylesheet" href="w3.css"/>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    </head>
    <body>
        <div class="w3-card-4">

        <header class="w3-container w3-pale-red">
          <h1 class="w3-center">${pessoa.nome}</h1>
        </header>

        <ul class="w3-ul w3-card-4 w3-hoverable " style="width:100%">
            <li><b>Idade: </b> ${pessoa.idade}</li>
            <li><b>Sexo: </b> ${pessoa.sexo}</li>
            <li><b>Morada: </b> ${pessoa.morada.cidade} - ${pessoa.morada.distrito}</li>
            <li><b>BI: </b> ${pessoa.BI}</li>
            <li><b>Descrição: </b> ${pessoa.descrição}</li>
            <li><b>Profissão: </b> ${pessoa.profissao}</li>
            <li><b>Partido Político: </b> ${pessoa.partido_politico.party_abbr} - ${pessoa.partido_politico.party_name}</li>
            <li><b>Marca do carro: </b>${pessoa.marca_carro}</li>
            <li><b>Desportos:</b>
            `
        
        for(let i = 0; i < pessoa.desportos.length ; i++){
            pagHTML += ` ${pessoa.desportos[i]}`
            if(i < pessoa.desportos.length - 1) pagHTML += `, `
        }
        
        pagHTML += `</li>
        <li><b>Animais:</b>
        `
        for(let i = 0; i < pessoa.animais.length ; i++){
            pagHTML += ` ${pessoa.animais[i]}`
            if(i < pessoa.animais.length - 1) pagHTML += `, `
        }

        pagHTML += `</li>
        <li><b>Figuras públicas PT:</b>
        `

        for(let i = 0; i < pessoa.figura_publica_pt.length ; i++){
            pagHTML += ` ${pessoa.figura_publica_pt[i]}`
            if(i < pessoa.figura_publica_pt.length - 1) pagHTML += `, `
        }

        pagHTML += `</li>
        <li><b>Destinos favoritos:</b>
        `

        for(let i = 0; i < pessoa.destinos_favoritos.length ; i++){
            pagHTML += ` ${pessoa.destinos_favoritos[i]}`
            if(i < pessoa.destinos_favoritos.length - 1) pagHTML += `, `
        }

        pagHTML += `</li>    
            </ul>


        <div class="w3-container w3-margin-top">
            <table class="w3-table-all w3-centered w3-hoverable w3-large" style="width: 100%;">
            <tr>
              <th>Fumador</th>
              <th>Gosta de cinema</th>
              <th>Gosta de viajar</th>
              <th>Acorda cedo</th>
              <th>Gosta de ler</th>
              <th>Gosta de música</th>
              <th>Gosta de comer</th>
              <th>Gosta de animais de estimação</th>
              <th>Gosta de dançar</th>
              <th>Comida Favorita</th>
            </tr>
            <tr>`

            for(var key in pessoa.atributos){
                if(pessoa.atributos[key] === true){
                    pagHTML += `<th><i class="fa-light fa-thumbs-up w3-green"></i></th>`
                }
                else if(pessoa.atributos[key] === false){
                    pagHTML += `<th><i class="fa-light fa-thumbs-down w3-red"></i></th>`
                }
                else {
                    pagHTML += `<th>${pessoa.atributos[key]}</th>`
                }
            }    
        
        pagHTML += `</tr></table></div>
        <footer class="w3-container w3-pale-red w3-center">
          <h5>Generated by pessoas-server: ${data}</h5>
          <h4><a href="http://localhost:7777/">Voltar ao Menu</a><h4>
        </footer>

        </div>
        
    </body>
</html>
    `

    return pagHTML
}

exports.genOptionsPage = function(data){
    var pagHTML = `
    <!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>About people</title>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4 w3-center">

        <header class="w3-container w3-pale-red">
          <h1>Menu</h1>
        </header>

        <div class="w3-container" style="margin-left:0;margin-right:0">
            <div class="w3-ul w3-card-4 w3-hoverable w3-center" style="width:100%" >
                <ul class="w3-ul">
                    <li><a href="http://localhost:7777/pessoas">Lista de todas as pessoas por ordem crescente</a></li>
                    <li><a href="http://localhost:7777/pessoas/ordDesc">Lista de todas as pessoas por ordem decrescente</a></li>
                    <li><a href="http://localhost:7777/dist/sexo">Distribuição por sexo</a></li>
                    <li><a href="http://localhost:7777/dist/desporto">Distribuição por desporto</a></li>
                    <li><a href="http://localhost:7777/top/profissoes">Top 10 profissões</a></li>
                </ul>
            </div>
        </div>

        <footer class="w3-container w3-pale-red">
          <h5>Generated by pessoas-server: ${data}</h5>
        </footer>

        </div>
        
    </body>
</html>`

return pagHTML

}

exports.distSexo = function(lista, data){
    const dist = new Map()
    let total = lista.length
    
    lista.forEach((pessoa) => {
        if(!dist.has(pessoa.sexo)){
            dist.set(pessoa.sexo, 0)
        }
        let n = dist.get(pessoa.sexo)
        dist.set(pessoa.sexo,++n)
    })

    for (const [key, value] of dist.entries()) {
        dist.set(key,(value/total)*100)
    };

    var pagHTML = `
    <!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>About people</title>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4 w3-center">

        <header class="w3-container w3-pale-red">
          <h1>Distribuição de pessoas por sexo</h1>
        </header>

        <div class="w3-container">
            <table class="w3-table-all w3-centered w3-hoverable w3-large">
            <tr>
              <th>Sexo</th>
              <th>%</th>
            </tr>`
        
    for (const [key, value] of dist.entries()) {
        pagHTML+= `<tr>
                <td><a href="http://localhost:7777/sexo/${key}">${key}</a></td>
                <td>${value.toFixed(4)}</td>
                </tr>`
    };
    
    pagHTML+= `
            </table>
        </div>

        <footer class="w3-container w3-pale-red w3-center">
          <h5>Generated by pessoas-server: ${data}</h5>
          <h4><a href="http://localhost:7777/">Voltar ao Menu</a><h4>
        </footer>

        </div>
        
    </body>
</html>
    `    

    

return pagHTML
    
}

exports.distDesporto = function(lista,data){
    const dist = new Map()
    let total = lista.length
    
    lista.forEach((pessoa) => {
        let desportos = pessoa.desportos
        desportos.forEach((d) => {
            if(!dist.has(d)){
                dist.set(d, 0)
            }
            let n = dist.get(d)
            dist.set(d,++n)
        })
        
    })

    for (const [key, value] of dist.entries()) {
        dist.set(key,(value/total)*100)
    };

    var pagHTML = `
    <!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>About people</title>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4 w3-center">

        <header class="w3-container w3-pale-red">
          <h1>Distribuição de pessoas por desporto</h1>
        </header>

        <div class="w3-container">
            <table class="w3-table-all w3-centered w3-hoverable w3-large">
            <tr>
              <th>Desporto</th>
              <th>%</th>
            </tr>`
        
    for (const [key, value] of dist.entries()) {
        
        let encoded = encodeURIComponent(key)
        pagHTML+= `<tr>
                <td><a href="http://localhost:7777/desporto/${encoded}">${key}</a></td>
                <td>${value.toFixed(4)}</td>
                </tr>`
    };
    
    pagHTML+= `
            </table>
        </div>

        <footer class="w3-container w3-pale-red w3-center">
          <h5>Generated by pessoas-server: ${data}</h5>
          <h4><a href="http://localhost:7777/">Voltar ao Menu</a><h4>
        </footer>

        </div>
        
    </body>
</html>
    `    

    

return pagHTML
}

exports.top10Profissoes = function(lista, data){
    dist = new Map()
    
    lista.forEach((pessoa) => {
        if(!dist.has(pessoa.profissao)){
            dist.set(pessoa.profissao, 0)
        }
        let n = dist.get(pessoa.profissao)
        dist.set(pessoa.profissao,++n)
    })


    const mapSort = new Map([...dist.entries()].sort((a, b) => b[1] - a[1]));

    const top10 = Array.from(mapSort).slice(0,10)
    
    var pagHTML = `
    <!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>About people</title>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4 w3-center">

        <header class="w3-container w3-pale-red">
          <h1>Top 10 Profissões</h1>
        </header>

        <div class="w3-container">
            <table class="w3-table-all w3-centered w3-hoverable w3-large">
            <tr>
              <th>Profissão</th>
              <th>Quantidade de pessoas</th>
            </tr>`
        
    for (let i = 0 ; i < top10.length ; i++) {
       
        let encoded = encodeURIComponent(top10[i][0])
        pagHTML+= `<tr>
                <td><a href="http://localhost:7777/profissoes/${encoded}">${top10[i][0]}</a></td>
                <td>${top10[i][1]}</td>
                </tr>`
    };
    
    pagHTML+= `
            </table>
        </div>

        <footer class="w3-container w3-pale-red w3-center">
          <h5>Generated by pessoas-server: ${data}</h5>
          <h4><a href="http://localhost:7777/">Voltar ao Menu</a><h4>
        </footer>

        </div>
        
    </body>
</html>
    `    

    

return pagHTML

}

